---
swagger: "2.0"
info:
  description: "This is a backoffice for the platform used to run Academany"
  version: "1.0.0"
  title: "Academany Management Platform"
host: "virtserver.swaggerhub.com"
basePath: "/fibasile/nueval/1.0.0"
schemes:
- "https"
security:
- password:
  - "read"
  - "write"
paths:
  /courses:
    get:
      summary: "List courses on the platform"
      description: "This method returns an array of Course objects"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/course"
    post:
      summary: "Create a new course on the platform"
      description: "A new Course is created based on the provided parameters"
      parameters: []
      responses:
        200:
          description: "OK"
        501:
          description: "Missing a key parameter"
  /ping:
    get:
      summary: "Server heartbeat operation"
      description: "This operation shows how to override the global security defined\
        \ above, as we want to open it up for all users."
      parameters: []
      responses:
        200:
          description: "OK"
      security: []
securityDefinitions:
  password:
    type: "oauth2"
    tokenUrl: "http://api.academany.org/oauth/token"
    flow: "password"
    scopes:
      write: "allows modifying resources"
      read: "allows reading resources"
definitions: {}
